name: flutter_assessment
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.10
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.10+1
  flutter_staggered_grid_view: ^0.7.0
  get_it: ^7.2.0
  injectable: ^2.1.1
  flutter_hooks: ^0.18.0
  #  location: ^7.0.0
  flutter_map: ^7.0.2
  geocoding: ^3.0.0
  geolocator: ^13.0.1
  latlong2: ^0.9.1
  flutter_map_location_marker: ^9.1.1
  loading_animation_widget: ^1.3.0
  hooks_riverpod: ^2.6.1
  carousel_slider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  injectable_generator: ^2.4.1
  build_runner: ^2.3.3

flutter:
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Euclid Circular A
      fonts:
        - asset: assets/fonts/Euclid Circular A Bold.ttf
        - asset: assets/fonts/Euclid Circular A Bold Italic.ttf
        - asset: assets/fonts/Euclid Circular A Italic.ttf
        - asset: assets/fonts/Euclid Circular A Light.ttf
        - asset: assets/fonts/Euclid Circular A Light Italic.ttf
        - asset: assets/fonts/Euclid Circular A Medium.ttf
        - asset: assets/fonts/Euclid Circular A Medium Italic.ttf
        - asset: assets/fonts/Euclid Circular A Regular.ttf
        - asset: assets/fonts/Euclid Circular A SemiBold.ttf
        - asset: assets/fonts/Euclid Circular A SemiBold Italic.ttf
#           style: italic
